# Generated by Django 4.2.23 on 2025-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='cart_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
