# Generated by Django 4.2.22 on 2025-06-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contact_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='NewsLetterModel',
        ),
    ]
