# Generated by Django 4.2 on 2025-08-22 13:59

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[accounts.validators.validate_iranian_phone]),
        ),
    ]
