# Generated by Django 4.2 on 2025-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
