# Generated by Django 4.2.22 on 2025-06-08 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
