# Generated by Django 4.2 on 2025-09-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=2),
        ),
    ]
