# Generated by Django 4.2.22 on 2025-06-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='breif_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
