# Generated by Django 4.2 on 2025-09-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productmodel_options_alter_productmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Show'), (2, 'Hide')], default=2),
        ),
    ]
