# Generated by Django 4.2 on 2025-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productimagemodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='product/extra-img/'),
        ),
    ]
