# Generated by Django 4.2 on 2025-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, default='/default/product-image.png', null=True, upload_to='product/img/'),
        ),
    ]
