# Generated by Django 4.2 on 2025-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
