# Generated by Django 4.2 on 2025-09-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productimagemodel_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodeltranslation',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategorymodeltranslation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
