# Generated by Django 4.2.23 on 2025-07-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_at']},
        ),
    ]
